### ISSUE TITLE
-baker-page-screenshots

### ISSUE THREAD

**Issue by Mazzy71** [bakerframework/baker-android#91]
Hi!

I've set -baker-page-screenshots with screenshots directory, but Baker doesn't generate anything, when i'm navigating thru my issue.. Files name is screenshot-landscape-X.jpg and screenshot-portrait-X.jpg

Does -baker-page-screenshots work for android baker?

**Comment by fcontreras** [comment]
Greetings @wmaznas,

unfortunately no, that feature is not yet available on Baker Android

**Comment by Mazzy71** [comment]
Thank You for quick answer.

let me do a little off topic:
It will be able in Baker Refactor?
In Your opinion, Refactor is stable enough to use it now instead of baker-android for this moment?
which other extension parameters are not available in android version of baker?

kindest regards!:)

**Comment by fcontreras** [comment]
1. The idea is at some point reach Baker iOS in all its features, when? that something we don't know yet but hopefully soon.
2. My current understanding about baker-refactor is that it still have some small bugs that keeps it unstable but thats a question that @tobiasstrebitzer might answer better since he has been hard working on it.
3. Well, baker Android is still young I must say, and we don't support any of this properties yet https://github.com/Simbul/baker/wiki/Book.json-baker-extension-parameters. Hopefully soon. :)
